version: "3.7"
services:
  mf-back:
    build:
      context: .
      dockerfile: .local/Dockerfile
    container_name: mf-back
    stdin_open: true
    ports:
      - 3030:3000
    volumes:
      - "./src:/app/src"
      - "./public:/app/public"
      - "./index.js:/app/index.js"
      - "./tsconfig.json:/app/tsconfig.json"
      - "./nodemon.json:/app/nodemon.json"
      - "./nestconfig.json:/app/nestconfig.json"
      - "./ormconfig.json:/app/ormconfig.json"
      - "node_modules:/app/node_modules"
      - "build:/app/build"
    networks:
      - mf
    labels:
      - traefik.http.routers.mf-back.rule=Host(`back.mf`)

  db:
    image: mysql:5.7
    container_name: mf-db
    environment:
      MYSQL_DATABASE: 'machine_fauna'
      MYSQL_USER: 'machine_fauna'
      MYSQL_PASSWORD: 'machine_fauna'
      MYSQL_ROOT_PASSWORD: 'machine_fauna'
    ports:
      - 3306:3306
    volumes:
      - "./database:/var/lib/mysql"
    networks:
      - mf
    labels:
      - traefik.enable=false

volumes:
  node_modules:
  build:

networks:
  mf:
    external: true