version: "3.7"
services:
  mf-back:
    build:
      context: .
      dockerfile: .github/Dockerfile
    container_name: mf-back
    restart: unless-stopped
    expose:
      - 3000
    healthcheck:
      test: "curl --fail localhost:3000/api/tags > /dev/null"
      interval: 5s
      timeout: 30s
      retries: 10
    networks:
      - mf
    labels:
      - traefik.http.routers.mf-back.rule=Host(`back.mf`)


networks:
  mf:
    external: true
